// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAUsTlUVNBr93TGtDptIV3cT9onq85dOuo',
    appId: '1:621781908676:web:4e6789326edbf7cc63dd91',
    messagingSenderId: '621781908676',
    projectId: 'astrozone-780a3',
    authDomain: 'astrozone-780a3.firebaseapp.com',
    storageBucket: 'astrozone-780a3.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBuGN4-JdEJT0Tl_NObqwbHoYT2Vy19fjY',
    appId: '1:621781908676:android:f0f2d2eda474442763dd91',
    messagingSenderId: '621781908676',
    projectId: 'astrozone-780a3',
    storageBucket: 'astrozone-780a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCXOPJhApXP3ayYfYEGzvXs-zSioVqcmpw',
    appId: '1:621781908676:ios:d9e5d59c794d882f63dd91',
    messagingSenderId: '621781908676',
    projectId: 'astrozone-780a3',
    storageBucket: 'astrozone-780a3.appspot.com',
    iosClientId: '621781908676-t86stkgkd1ddt8cqbl9gl0ve0uisil8l.apps.googleusercontent.com',
    iosBundleId: 'com.example.astrozone',
  );
}
